export const DEAL_CATEGORIES = [
	'laptops',
	'electronics-home',
	'mobile-phones',
	'gadgets-accessories',
	'fashion',
	'lifestyle',
	'Best-Deals',
	'miscellaneous',
] as const;

export type DealCategory = (typeof DEAL_CATEGORIES)[number];

type DetectableCategory = Exclude<DealCategory, 'Best-Deals' | 'miscellaneous'>;

type CategoryRule = {
	category: DetectableCategory;
	keywords: readonly string[];
};

// Rules are ordered deliberately: specific accessories must be checked before
// the broader product words they contain (for example, "phone case" before "phone").
const CATEGORY_RULES: readonly CategoryRule[] = [
	{
		category: 'gadgets-accessories',
		keywords: [
			'phone screen protector',
			'wireless charger',
			'lightning cable',
			'bluetooth earphones',
			'gaming controller',
			'gaming mouse',
			'screen protector',
			'laptop cooling pad',
			'laptop sleeve',
			'laptop bag',
			'phone case',
			'phone cover',
			'phone stand',
			'mobile case',
			'mobile cover',
			'mobile stand',
			'fast charger',
			'usb charger',
			'type-c cable',
			'usb cable',
			'hdmi cable',
			'memory card',
			'fitness band',
			'smart watch',
			'smart-watch',
			'apple watch',
			'galaxy watch',
			'galaxy buds',
			'oneplus buds',
			'vr headset',
			'cooling pad',
			'power bank',
			'mouse pad',
			'usb drive',
			'sd card',
			'earphones',
			'headphones',
			'earbuds',
			'airpods',
			'neckband',
			'smartwatch',
			'charger',
			'chargers',
			'cable',
			'adapter',
			'printer',
			'monitor',
			'moniter',
			'pendrive',
			'pen drive',
			'keyboard',
			'mouse',
			'tablet',
			'ipad',
			'hdd',
			'ssd',
			'tws',
		],
	},
	{
		category: 'lifestyle',
		keywords: [
			'automatic watch',
			'mechanical watch',
			'chronograph watch',
			'classic watch',
			'analog watch',
			'analogue watch',
			'quartz watch',
			'wrist watch',
			'formal shoes',
			'running shoes',
			'walking shoes',
			'sports shoes',
			'trekking shoes',
			'trolley bags',
			'trolley bag',
			'travel bags',
			'travel bag',
			'duffel bags',
			'duffel bag',
			'duffle bags',
			'duffle bag',
			'eau de parfum',
			'eau de toilette',
			'body spray',
			'flip-flops',
			'suitcase',
			'suitcases',
			'luggage',
			'backpack',
			'handbag',
			'clutch',
			'wallet',
			'wallets',
			'perfume',
			'perfumes',
			'fragrance',
			'fragrances',
			'cologne',
			'deodorant',
			'attar',
			'sneakers',
			'sneaker',
			'shoes',
			'shoe',
			'boots',
			'boot',
			'heels',
			'sandals',
			'slippers',
			'loafers',
			'clogs',
			'watches',
			'watch',
			'sunglasses',
			'jewelry',
			'jewellery',
			'necklace',
			'bracelet',
			'earrings',
			'bangles',
			'rings',
			'belts',
			'belt',
			'hat',
			'cap',
		],
	},
	{
		category: 'laptops',
		keywords: [
			'surface laptop',
			'gaming laptop',
			'gaming notebook',
			'apple macbook',
			'chromebook',
			'ultrabook',
			'macbook',
			'thinkpad',
			'ideapad',
			'vivobook',
			'zenbook',
			'probook',
			'inspiron',
			'latitude',
			'spectre',
			'pavilion',
			'predator',
			'helios',
			'legion',
			'laptop',
			'notebook',
			'omen',
			'nitro',
			'razer blade',
			'galaxy book',
			'rog',
			'tuf',
		],
	},
	{
		category: 'mobile-phones',
		keywords: [
			'asus rog phone',
			'foldable phone',
			'flagship phone',
			'budget phone',
			'mid-range phone',
			'flip phone',
			'mobile phone',
			'google pixel',
			'sony xperia',
			'nothing phone',
			'5g phone',
			'smartphone',
			'iphone',
			'oneplus',
			'redmi',
			'galaxy',
			'realme',
			'motorola',
			'infinix',
			'tecno',
			'iqoo',
			'poco',
			'oppo',
			'vivo',
			'nokia',
			'phone',
			'mobile',
		],
	},
	{
		category: 'electronics-home',
		keywords: [
			'induction cooktop',
			'washing machine',
			'air conditioner',
			'inverter ac',
			'split ac',
			'window ac',
			'water purifier',
			'vacuum cleaner',
			'electric iron',
			'steam iron',
			'mixer grinder',
			'refrigerator',
			'home theatre',
			'home theater',
			'coffee maker',
			'deep freezer',
			'google home',
			'air fryer',
			'rice cooker',
			'smart home',
			'microwave',
			'dishwasher',
			'smart tv',
			'soundbar',
			'television',
			'fridge',
			'speaker',
			'geyser',
			'cooler',
			'blender',
			'juicer',
			'toaster',
			'ceiling fan',
			'table fan',
			'pedestal fan',
			'exhaust fan',
			'mattress',
			'pillow',
			'chimney',
			'heater',
			'freezer',
			'qled',
			'oled',
			'uhd tv',
			'led tv',
			'sofa',
			'oven',
			'tv',
			'alexa',
			'amazon echo',
			'ac',
		],
	},
	{
		category: 'fashion',
		keywords: [
			'men clothing',
			"men's clothing",
			'women clothing',
			"women's clothing",
			'ethnic wear',
			'formal wear',
			'casual wear',
			't-shirt',
			't shirt',
			'tshirt',
			'innerwear',
			'nightwear',
			'sportswear',
			'underwear',
			'lingerie',
			'clothing',
			'trousers',
			'leggings',
			'sweater',
			'shirt',
			'jeans',
			'pants',
			'shorts',
			'skirt',
			'dress',
			'jacket',
			'blazer',
			'hoodie',
			'coat',
			'suit',
			'kurta',
			'saree',
			'lehenga',
			'salwar',
			'socks',
		],
	},
];

const normalize = (value: string): string =>
	value
		.normalize('NFKC')
		.toLowerCase()
		.replace(/[\u2010-\u2015]/g, '-')
		.replace(/[\u2018\u2019]/g, "'")
		.replace(/\s+/g, ' ')
		.trim();

const escapeRegex = (value: string): string =>
	value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const COMPILED_RULES = CATEGORY_RULES.flatMap(({ category, keywords }) =>
	[...keywords]
		.sort((left, right) => right.length - left.length)
		.map((keyword) => ({
			category,
			pattern: new RegExp(
				`(?:^|[^\\p{L}\\p{N}])${escapeRegex(normalize(keyword))}(?=$|[^\\p{L}\\p{N}])`,
				'u',
			),
		})),
);

/** Detect a product category from deal text. */
export function detectCategory(text: string): DealCategory {
	const normalizedText = normalize(text);
	const match = COMPILED_RULES.find(({ pattern }) => pattern.test(normalizedText));
	return match?.category ?? 'miscellaneous';
}
