apiVersion: apps/v1
kind: Deployment
metadata:
  name: deals24-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deals24-frontend
  template:
    metadata:
      labels:
        app: deals24-frontend
    spec:
      containers:
        - name: frontend
          image: harishuptodate/deals24-frontend:v4
          env:
          - name: VITE_API_BASE_URL
            value: "http://localhost:30800/api"
          - name: VITE_ADMIN_USERNAME
            value: "harish"
          - name: VITE_ADMIN_PASSWORD
            value: "https://f065-106-222-228-41.ngrok-free.app"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  # type: LoadBalancer  #comment or remove nodeport port 
  selector:
    app: deals24-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30808 # Exposed on localhost:30808
